import { FundingCard } from '../types';

function pad2(n: number): string {
  return String(n).padStart(2, '0');
}

function formatDateAsYYYYMMDD(d: Date): string {
  return `${d.getFullYear()}${pad2(d.getMonth() + 1)}${pad2(d.getDate())}`;
}

// Try to parse common deadline formats that appear in scraped content.
// Falls back to null if parsing fails.
export function parseDeadlineToDate(deadline: string): Date | null {
  if (!deadline) return null;
  const raw = String(deadline).trim();
  if (!raw || raw.toLowerCase() === 'n/a') return null;

  // Normalize whitespace and separators.
  const s = raw
    .replace(/\u00A0/g, ' ')
    .replace(/\s+/g, ' ')
    .replace(/\./g, '-')
    .trim();

  // 1) ISO-ish: YYYY-MM-DD
  {
    const m = s.match(/\b(\d{4})-(\d{1,2})-(\d{1,2})\b/);
    if (m) {
      const yyyy = Number(m[1]);
      const mm = Number(m[2]);
      const dd = Number(m[3]);
      const dt = new Date(yyyy, mm - 1, dd);
      if (!Number.isNaN(dt.getTime())) return dt;
    }
  }

  // 2) EU: DD-MM-YYYY or DD/MM/YYYY
  {
    const m = s.match(/\b(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})\b/);
    if (m) {
      const dd = Number(m[1]);
      const mm = Number(m[2]);
      const yyyy = Number(m[3]);
      const dt = new Date(yyyy, mm - 1, dd);
      if (!Number.isNaN(dt.getTime())) return dt;
    }
  }

  // 3) “DD Month YYYY” (English)
  {
    const m = s.match(/\b(\d{1,2})\s+(Jan|January|Feb|February|Mar|March|Apr|April|May|Jun|June|Jul|July|Aug|August|Sep|Sept|September|Oct|October|Nov|November|Dec|December)\s+(\d{4})\b/i);
    if (m) {
      const dd = Number(m[1]);
      const mon = m[2].toLowerCase();
      const yyyy = Number(m[3]);
      const monthMap: Record<string, number> = {
        jan: 0, january: 0,
        feb: 1, february: 1,
        mar: 2, march: 2,
        apr: 3, april: 3,
        may: 4,
        jun: 5, june: 5,
        jul: 6, july: 6,
        aug: 7, august: 7,
        sep: 8, sept: 8, september: 8,
        oct: 9, october: 9,
        nov: 10, november: 10,
        dec: 11, december: 11,
      };
      const mm = monthMap[mon];
      if (mm !== undefined) {
        const dt = new Date(yyyy, mm, dd);
        if (!Number.isNaN(dt.getTime())) return dt;
      }
    }
  }

  // 4) Last resort: Date.parse
  {
    const t = Date.parse(s);
    if (!Number.isNaN(t)) return new Date(t);
  }

  return null;
}

function escapeICSText(text: string): string {
  // RFC5545 text escaping: backslash, comma, semicolon, newline
  return String(text)
    .replace(/\\/g, '\\\\')
    .replace(/\n/g, '\\n')
    .replace(/,/g, '\\,')
    .replace(/;/g, '\\;');
}

export function buildFundingDeadlineICS(card: FundingCard, opts?: { now?: Date }): { ics: string; filename: string } {
  const now = opts?.now ?? new Date();
  const uid = `${card.id || 'funding'}-${now.getTime()}@eu-call-finder`;

  const dtStampUtc = new Date(now.getTime() - now.getTimezoneOffset() * 60_000)
    .toISOString()
    .replace(/[-:]/g, '')
    .replace(/\.\d{3}Z$/, 'Z');

  const deadlineDate = parseDeadlineToDate(card.deadline) ?? now;
  const startYYYYMMDD = formatDateAsYYYYMMDD(deadlineDate);
  const endDate = new Date(deadlineDate.getFullYear(), deadlineDate.getMonth(), deadlineDate.getDate() + 1);
  const endYYYYMMDD = formatDateAsYYYYMMDD(endDate);

  const title = card.title ? `EU Call Deadline: ${card.title}` : 'EU Call Deadline';
  const descriptionLines: string[] = [];
  if (card.programme) descriptionLines.push(`Programme: ${card.programme}`);
  if (card.budget) descriptionLines.push(`Budget: ${card.budget}`);
  if (card.contribution) descriptionLines.push(`EU Contribution: ${card.contribution}`);
  if (card.deadline) descriptionLines.push(`Deadline: ${card.deadline}`);
  if (card.url) descriptionLines.push(`Link: ${card.url}`);
  descriptionLines.push('');
  descriptionLines.push('Generated by EU Call Finder');

  const ics = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//EU Call Finder//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'BEGIN:VEVENT',
    `UID:${escapeICSText(uid)}`,
    `DTSTAMP:${dtStampUtc}`,
    `SUMMARY:${escapeICSText(title)}`,
    // All-day event
    `DTSTART;VALUE=DATE:${startYYYYMMDD}`,
    `DTEND;VALUE=DATE:${endYYYYMMDD}`,
    `DESCRIPTION:${escapeICSText(descriptionLines.join('\n'))}`,
    // Google Calendar typically respects URL as clickable
    card.url ? `URL:${escapeICSText(card.url)}` : null,
    'END:VEVENT',
    'END:VCALENDAR',
  ].filter(Boolean).join('\r\n');

  const safeId = (card.id || 'eu-call').replace(/[^a-zA-Z0-9_-]+/g, '_');
  const filename = `eu-call-deadline-${safeId}.ics`;
  return { ics, filename };
}

export function downloadICS(filename: string, ics: string): void {
  const blob = new Blob([ics], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  try {
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
  } finally {
    URL.revokeObjectURL(url);
  }
}
